name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    name: Run QuickCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10.3'
          cabal-version: '3.16.1.0'

      - run: cabal update
      - run: cabal build -v3 --only-dependencies --enable-tests
      - run: cabal test -v3
